CMDOC_DEST_DIR = strip

WD	= /client/javascript/common

JAVA_ROOT = y:/tools/cmdoc

THIS_CODE = BrowserSense.js GeneralPurpose.js Hot.js

include y:/tools/makefiles/java.make
include y:/tools/makefiles/cmdoc.make
