SRC =	adzogbo.html bios.html codedMessages.html construct.html \
	francis.html francisBio.html francisResume.html friends.html \
        gadzo.html greet.html help.html i.html index.html info.html \
	libation.html links.html margin.html nante.html news.html \
	performCenter.html slaveStats.html support.html tele.html \
	theCode.html vuGbe.html wall.html wallBottom.html wallHeart.html \
	wallTop.html whip.html 


ci:	
	$(foreach X, $(SRC), $(shell ci -l $X))
